# Generated by Django 4.1.4 on 2022-12-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
